/*
  Copyright 2019 Amazon.com, Inc. or its affiliates. All Rights Reserved.
  Permission is hereby granted, free of charge, to any person obtaining a copy of this
  software and associated documentation files (the "Software"), to deal in the Software
  without restriction, including without limitation the rights to use, copy, modify,
  merge, publish, distribute, sublicense, and/or sell copies of the Software, and to
  permit persons to whom the Software is furnished to do so.
  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
  INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
  PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
  HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
  OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
  SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
*/

#include <pgmspace.h>

#define SECRET
#define THINGNAME "ESP32_MQTT"

const char WIFI_SSID[] = "TP_Link_Living";
const char WIFI_PASSWORD[] = "20210722";
const char AWS_IOT_ENDPOINT[] = "a3aol58i7bjuew-ats.iot.ap-northeast-1.amazonaws.com";

// Amazon Root CA 1
static const char AWS_CERT_CA[] PROGMEM =
  R"EOF(
-----BEGIN CERTIFICATE-----
MIIDQTCCAimgAwIBAgITBmyfz5m/jAo54vB4ikPmljZbyjANBgkqhkiG9w0BAQsF
ADA5MQswCQYDVQQGEwJVUzEPMA0GA1UEChMGQW1hem9uMRkwFwYDVQQDExBBbWF6
b24gUm9vdCBDQSAxMB4XDTE1MDUyNjAwMDAwMFoXDTM4MDExNzAwMDAwMFowOTEL
MAkGA1UEBhMCVVMxDzANBgNVBAoTBkFtYXpvbjEZMBcGA1UEAxMQQW1hem9uIFJv
b3QgQ0EgMTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBALJ4gHHKeNXj
ca9HgFB0fW7Y14h29Jlo91ghYPl0hAEvrAIthtOgQ3pOsqTQNroBvo3bSMgHFzZM
9O6II8c+6zf1tRn4SWiw3te5djgdYZ6k/oI2peVKVuRF4fn9tBb6dNqcmzU5L/qw
IFAGbHrQgLKm+a/sRxmPUDgH3KKHOVj4utWp+UhnMJbulHheb4mjUcAwhmahRWa6
VOujw5H5SNz/0egwLX0tdHA114gk957EWW67c4cX8jJGKLhD+rcdqsq08p8kDi1L
93FcXmn/6pUCyziKrlA4b9v7LWIbxcceVOF34GfID5yHI9Y/QCB/IIDEgEw+OyQm
jgSubJrIqg0CAwEAAaNCMEAwDwYDVR0TAQH/BAUwAwEB/zAOBgNVHQ8BAf8EBAMC
AYYwHQYDVR0OBBYEFIQYzIU07LwMlJQuCFmcx7IQTgoIMA0GCSqGSIb3DQEBCwUA
A4IBAQCY8jdaQZChGsV2USggNiMOruYou6r4lK5IpDB/G/wkjUu0yKGX9rbxenDI
U5PMCCjjmCXPI6T53iHTfIUJrU6adTrCC2qJeHZERxhlbI1Bjjt/msv0tadQ1wUs
N+gDS63pYaACbvXy8MWy7Vu33PqUXHeeE6V/Uq2V8viTO96LXFvKWlJbYK8U90vv
o/ufQJVtMVT8QtPHRh8jrdkPSHCa2XV4cdFyQzR1bldZwgJcJmApzyMZFo6IQ6XU
5MsI+yMRQ+hDKXJioaldXgjUkK642M4UwtBV8ob2xJNDd2ZhwLnoQdeXeGADbkpy
rqXRfboQnoZsG4q5WTP468SQvvG5
-----END CERTIFICATE-----
)EOF";

// Device Certificate
static const char AWS_CERT_CRT[] PROGMEM =
  R"KEY(
-----BEGIN CERTIFICATE-----
MIIDWjCCAkKgAwIBAgIVAKY0OhkFkbI8sWz+FNdhji5JnLT0MA0GCSqGSIb3DQEB
CwUAME0xSzBJBgNVBAsMQkFtYXpvbiBXZWIgU2VydmljZXMgTz1BbWF6b24uY29t
IEluYy4gTD1TZWF0dGxlIFNUPVdhc2hpbmd0b24gQz1VUzAeFw0yMjAyMDcxNDI3
MDFaFw00OTEyMzEyMzU5NTlaMB4xHDAaBgNVBAMME0FXUyBJb1QgQ2VydGlmaWNh
dGUwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDDtbD0lXUrxMGSatJO
3HzHSthYqJQXhm1BDTST2Dhm+WRIiGx3g5Km7ABxKmO+spe5QMe3eut5HzEuGJT9
pp40Qcq0WAga41HSu18yZ85TX+NdZY2dDNtn5Scl3r/RyoVNGZlqH0eR4npS6x2z
NdSvTYdH8JqVrcis1qUyupdzJi1QddBzOdeWOXLBbYuM8Ye5jmLvOMM9FpLyxBcZ
YOy8kPBydZpZLYlI1uX7MW2zHxRt2yUh1ZoUgJWkzWGRMABFk23VZ3XD9g/lQj6Z
Zx1oFeAsQ5hAUK+chjG0yj3TIQ2+YhWQXmHyGWrjfLi+pD9eTR133P/lBObbEFR/
quh3AgMBAAGjYDBeMB8GA1UdIwQYMBaAFGf+tvQo6VzcJiNTD3w+V3lMYhRTMB0G
A1UdDgQWBBQwu+ublVX8LX78i+MOWangl9q0njAMBgNVHRMBAf8EAjAAMA4GA1Ud
DwEB/wQEAwIHgDANBgkqhkiG9w0BAQsFAAOCAQEAgzkNogxi0Fo6ZS2HZeL8WmPy
lhUzbU7ScbuvtNvrBe8fj7zmjsWbx64ZemHpPnECGuJA3agsAvD/5PQYI2S5kCpq
/Pei+fPPkWDH8b5IczIWuNguflXNy+FJw06HoRo/CQPN35OwehMNDni0Y2VkXwke
a6qPH+Uamsow6Lk7afBZMsgUXfokYAlrKk9sWsoisd3aICbPcLhhzjGReRf2dzh7
kk/1QLBWu5hSfb1EOXSA6u5XYMNtbhKjmwaUzv+qQyGUDjdK0zL9kHS9BIxUolwz
cRKdG9GNFaJxiNQB9eIJ10LVwY5gh3ibdzaYsUefV1/UF1ZZtLoJoUOJocQXRQ==
-----END CERTIFICATE-----

)KEY";

// Device Private Key
static const char AWS_CERT_PRIVATE[] PROGMEM =
  R"KEY(
-----BEGIN RSA PRIVATE KEY-----
MIIEowIBAAKCAQEAw7Ww9JV1K8TBkmrSTtx8x0rYWKiUF4ZtQQ00k9g4ZvlkSIhs
d4OSpuwAcSpjvrKXuUDHt3rreR8xLhiU/aaeNEHKtFgIGuNR0rtfMmfOU1/jXWWN
nQzbZ+UnJd6/0cqFTRmZah9HkeJ6UusdszXUr02HR/Cala3IrNalMrqXcyYtUHXQ
cznXljlywW2LjPGHuY5i7zjDPRaS8sQXGWDsvJDwcnWaWS2JSNbl+zFtsx8Ubdsl
IdWaFICVpM1hkTAARZNt1Wd1w/YP5UI+mWcdaBXgLEOYQFCvnIYxtMo90yENvmIV
kF5h8hlq43y4vqQ/Xk0dd9z/5QTm2xBUf6rodwIDAQABAoIBACKGJa4vw1iyP9d9
YpYozRY2/M0/B8jSnOlR1AmUpfZ8XhVxg3jdy/wIO9e6u5fDV4KFi/WxCGL4fqt8
CKRqRRRA2upPcTaVDTUYeqWgrEQG8Uvjg0TGJNpCEVLb5Yizqio8rtSKqgxxIFUK
RtX7VAaMraWiKxLmcjUTNFcrlVXpggwf8ECZpBrP+Cl+A0AuS5fFdDytxIuAEFX8
UnTdB3qYu+t+vv3FSsqJ9ktF+iauURA7Q/yNwMkPOXAqNvS1FE9Gt+P/GAm+5JrP
My6BSqAgWWiZSoHWhNAvBz0S3IQIi4JrmSkTt3IDa4ji9O7CvOetFenjsM/Eryhc
ZE8Mx9ECgYEA7fxtyuvVgEdaK1A26Bs0cWnMT6tDGWOT1I3457Vliy3gerlvlfkc
DgCY4X87vgKziMfh355pCYgIJKWtxbF40bAMBr6B0JH+32KmP8wtVoWQ1y6wq7po
nWyuJKrf+WYTp/jqnA67oFrFz5+u3hEoet3g+FeglsA29aYgGFR5BxkCgYEA0oYN
uetZhPrbwkLztGE1IbEZeaGrohJF4AdKJUn/OfkmbbOmacfZIuOxyXeAvM48psMK
bYfQcjG5/zy78E72ma8U8I/jlc8ecSdFqImW17+19dDDJmGGOh44pz5Cij8aeOdu
q7wehr1qjp07AMrxBjx8laMcwJP0EybSJkJVLg8CgYBLO9fBpJhT+zqIIs2YxrDn
gZizPuLxbcdYFKGxLmkxfIlQgrrB4IR78Lhj4QMT6Gq1POss9DkkaDqayz2KF7ao
I01J/IOxWdYG7Hq+BF/40DSfsgTr5PwZeDf9I3+2qgxgt5IDT60E3m1WW5a+YRI4
9VefaqQ7w/wb4C6ZQmsYUQKBgHogwGfBy23kpYYdlwlmdw8zkSbJjir4VMbxE6ds
NP7ptcxgMsMc569gzeulQu7E6dSIQ01lQ5xrko4qKpDvDgn70rb3kjx/KhbUhImQ
QAyrL6EJ2ZwzaU3f6FfFO469qtrGz6IbAM6DpgRT3D3KfWZzwoaAWJazfh16IOGH
C6krAoGBAL3TSvh3crhogl+p1uMw7hXArkIHIJ+bKRebQUyPlz3tiJl/MC+Xp21G
AUpiPBVCQgjqfBggLib7V0gSOe59fOhwVmRfUZjKmDHk+H0hVtpSnww+ZIsQqoKk
qEXB4deUfSuckhcEl9SjpEzFfiFHQzQT9BPCUK0ckPqGDGBNivyi
-----END RSA PRIVATE KEY-----

)KEY";
