on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

name: run build test
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Create dummy secrets.h
      run: mv .github/secrets.h include/secrets.h

    - name: install python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade platformio
    - name: Install library dependencies
      run: pio lib -g install 1
    - name: Run PlatformIO
      run: pio run
