on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

name: run build test
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: install python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: install platformio
      run: pip install platformio==5.0.3

    - name: build
      run: make ci
